files:
  - source: /en/*.json
    translation: /%locale%/%original_file_name%
    languages_mapping:
      locale:
        bg: bg-bg
        cs: cs-cz
        de: de-de
        el: el-gr
        es-ES: es-es
        fa: fa-ir
        fr: fr-fr
        hu: hu-hu
        id: id-id
        it: it-it
        ja: ja-jp
        ko: ko-kr
        nl: nl-nl
        pl: pl-pl
        pt-BR: pt-br
        pt-PT: pt-pt
        ro: ro-ro
        ru: ru-ru
        sr-SP: sr-sp
        tr: tr-tr
        th-TH: th-th
        uk: uk-ua
        ur-IN: ur-in
        ur-PK: ur-pk
        vi: vi-vn
        zh-CN: zh-cn
  - source: /en/*.md
    translation: /%locale%/%original_file_name%
    languages_mapping:
      locale:
        bg: bg-bg
        cs: cs-cz
        de: de-de
        el: el-gr
        es-ES: es-es
        fa: fa-ir
        fr: fr-fr
        hu: hu-hu
        id: id-id
        it: it-it
        ja: ja-jp
        ko: ko-kr
        nl: nl-nl
        pl: pl-pl
        pt-BR: pt-br
        pt-PT: pt-pt
        ro: ro-ro
        ru: ru-ru
        sr-SP: sr-sp
        tr: tr-tr
        th-TH: th-th
        uk: uk-ua
        ur-IN: ur-in
        ur-PK: ur-pk
        vi: vi-vn
        zh-CN: zh-cn
  - source: /en/api/*.md
    translation: /%locale%/api/%original_file_name%
    languages_mapping:
      locale:
        bg: bg-bg
        cs: cs-cz
        de: de-de
        el: el-gr
        es-ES: es-es
        fa: fa-ir
        fr: fr-fr
        hu: hu-hu
        id: id-id
        it: it-it
        ja: ja-jp
        ko: ko-kr
        nl: nl-nl
        pl: pl-pl
        pt-BR: pt-br
        pt-PT: pt-pt
        ro: ro-ro
        ru: ru-ru
        sr-SP: sr-sp
        tr: tr-tr
        th-TH: th-th
        uk: uk-ua
        ur-IN: ur-in
        ur-PK: ur-pk
        vi: vi-vn
        zh-CN: zh-cn
