files:
  - source: /en/*.json
    translation: /%locale%/%original_file_name%
  - source: /en/*.md
    translation: /%locale%/%original_file_name%
  - source: /en/api/*.md
    translation: /%locale%/api/%original_file_name%
